### ISSUE TITLE
Exception: Request failed, Non-200 received getting AUTH cookie: 403

### ISSUE THREAD

**Issue by mybig731** [ChuckMac/ADRFinder#10] opened 2022-11-08 02:08 UTC
Hey there.  App has been working great till this evening.  Seems that I am getting an error Exception: Request failed, Non-200 received getting AUTH cookie: 403 

The web interface is not reachable.  

Bummer on the timing as my trip begins on Friday....haha Figures!

**Comment by ChuckMac** [comment] 2022-11-08 13:55
Seeing the same error here too.  Will try to take a look into it.

**Comment by emusgrave** [comment] 2022-11-08 18:40
I cloned and ran the repo locally instead of with the Docker image, and it seems to be working fine with Python 3.10, so perhaps this can be fixed with a Dockerfile update?

In Postman, I did notice some problems POSTing to the auth url now if the headers aren't set properly...
```
headers = {
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36',
  'Accept-Language': 'en-US,en;q=0.9',
  'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'Host': 'disneyworld.disney.go.com'
}
```

**Comment by ChuckMac** [comment] 2022-11-08 20:10
@emusgrave thanks for checking on that.  Not sure why, but I updated the Python version in the image locally and it did indeed fix it.  Pushed an update out and should be in docker hub as well.

**Comment by dawnerd** [comment] 2022-11-08 21:00
Ran into the same problem and pulled latest docker but now its just hanging and timing out. Nothing in the docker logs other than the http requests.

If I open in a private window it loads the login page but once I type the correct pass thats when it stalls up.

**Comment by ChuckMac** [comment] 2022-11-09 01:03
@dawnerd I would say maybe try stop/remove/reup?  I tried it on 2 different machines (windows & linux) and it loads successfully on both.

**Comment by ChuckMac** [comment] 2023-03-09 15:43
closing for now as can't reproduce

**Closed by ChuckMac** 2023-03-09 15:43 UTC
